//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace threadingtest2.bankService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="bankService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/applyCCNumber", ReplyAction="http://tempuri.org/IService1/applyCCNumberResponse")]
        int applyCCNumber();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/applyCCNumber", ReplyAction="http://tempuri.org/IService1/applyCCNumberResponse")]
        System.Threading.Tasks.Task<int> applyCCNumberAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validateCCNumber", ReplyAction="http://tempuri.org/IService1/validateCCNumberResponse")]
        string validateCCNumber(string CCNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/validateCCNumber", ReplyAction="http://tempuri.org/IService1/validateCCNumberResponse")]
        System.Threading.Tasks.Task<string> validateCCNumberAsync(string CCNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : threadingtest2.bankService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<threadingtest2.bankService.IService1>, threadingtest2.bankService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int applyCCNumber() {
            return base.Channel.applyCCNumber();
        }
        
        public System.Threading.Tasks.Task<int> applyCCNumberAsync() {
            return base.Channel.applyCCNumberAsync();
        }
        
        public string validateCCNumber(string CCNumber) {
            return base.Channel.validateCCNumber(CCNumber);
        }
        
        public System.Threading.Tasks.Task<string> validateCCNumberAsync(string CCNumber) {
            return base.Channel.validateCCNumberAsync(CCNumber);
        }
    }
}
